version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5466:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: greenlight
      POSTGRES_DB: greenlight

  mail:
    container_name: mailpit
    image: axllent/mailpit
    restart: always
    ports:
      - "8025:8025" # web
      - "1025:1025"