version: '3'

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpass
      - POSTGRES_DB=greenlight
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - greenlight_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      # - GREENLIGHT_DB_DSN="host=db port=5432 user=greenlight dbname=greenlight password=pa55word sslmode=disable"
      - GREENLIGHT_DB_DSN=postgres://greenlight:pa55word@db:5432/greenlight?sslmode=disable
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - greenlight_net

networks:
  greenlight_net:
    driver: bridge
