version: '3'

dotenv:
  - ".env"

tasks:
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down 

  run:
    cmds:
      - go run ./cmd/api {{.CLI_ARGS}}

  build:
    cmds:
      - echo Building API
      - go build -ldflags='-s' -o=./bin/api ./cmd/api
      - GOOS=linux GOARCH=amd64 go build -ldflags='-s' -o=./bin/linux_amd64/api ./cmd/api

  migrate-up:
    cmd: migrate -path ./migrations -database=$GREENLIGHT_DB_DSN up

  migrate-down:
    cmd: migrate -path ./migrations -database=$GREENLIGHT_DB_DSN down

  migrate-drop:
    cmd: migrate -path ./migrations -database=$GREENLIGHT_DB_DSN drop -f

  new-migration:
    cmd: migrate create -seq -ext=.sql -dir=./migrations {{.CLI_ARGS}}
    
  audit:
    cmds:
      - echo Tidying and verifying module dependencies...
      - go mod tidy
      - go mod verify
      - echo Formatting code...
      - go fmt ./...
      - echo Vetting code...
      - go vet ./...
      - staticcheck ./...
      - echo Running tests
      - go test -race -vet=off ./...